exports.authentication = require('./modules/authentication/routes')
exports.user = require('./modules/user/routes')
exports.role = require('./modules/role/routes')
exports.module = require('./modules/module/routes')
exports.access = require('./modules/access/routes')
exports.version = require('./modules/version/routes')
